version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    restart: always
    command: npm start
    # Production doesn't mount volumes to avoid code changes affecting the running container

  db:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_NAME:-inventory_db}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # No ports exposed to the host in production for security
    ports: []
